### ISSUE TITLE
Selected text in IDE textboxes is barely visible

### ISSUE THREAD

**Issue by strakamichal** [nathcakes/Copilot-Dark-Theme-IntelliJ#1]
Hi,
love you theme, but I see one small issue. When I select any text in IDE (JetBrains Rider) the text has kind of wrong colour so it's almost not possible to see what's selected. Is it possible to change selected color to something lighter?

As you can see - word "text" is selected, but it's not visible.

![Snímek obrazovky 2022-07-22 v 18 09 50](https://user-images.githubusercontent.com/73341369/180480654-fda24823-ad1c-44cb-82fc-930bcf7f5504.png)

Thanks, Michal

**Comment by nathcakes** [comment]
I've submitted an update to the Marketplace to adjust the colours here to be a bit more visible. Hope you like it and feel free to reopen if it's still not suitable.

**Comment by nathcakes** [comment]
How interesting! I was playing around with it and it wasn't updating in my IDE, I think it might have been related to the icon pack I used. I'll revert it on the next update, it wasn't intended to be shipped.
